import Head from "next/head"
import Header from "../layout/Header"
import Footer from "../layout/Footer"
import { info } from "../interface/info"


import AboutPage from "../components/about/about_page"

const About = () => {
  return (
    <>
      <Head>
        <title>About me :)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="content">
        <AboutPage info={info} />
      </div>
      <Footer />
    </>
  )
}

export default About
