import Header from "../layout/Header"
import Head from "next/head"
import Footer from "../layout/Footer"
import PortfolioPage from "../components/portfolio/portfolio_page"
import { info } from "../interface/info"

const Portfolio = () => {
  return (
    <>
    <Head>
        <title>Portflio :)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="content">
        <PortfolioPage info={info} />
      </div>
      <Footer />
    </>
  )
}

export default Portfolio
